name: "$(SourceBranchName)+$(BuildID)"

trigger: none
pr: none

resources:
  repositories:
    - repository: common
      type: github
      name: NHSDigital/api-management-utils
      ref: APM-1646-debug
      endpoint: NHSDigital
  pipelines:
  - pipeline: build_pipeline
    source: "Personal-Demographics-Service-Build"
    trigger:
      branches:
        include:
          - refs/tags/v*

pool:
  vmImage: 'ubuntu-latest'

variables:
  - template: project.yml

extends:
  template: azure/common/apigee-deployment.yml@common
  parameters:
    service_name: ${{ variables.service_name }}
    short_service_name: ${{ variables.short_service_name }}
    service_base_path: ${{ variables.service_base_path }}
    product_display_name: ${{ variables.product_display_name }}
    product_description: ${{ variables.product_description }}
    spec_file: ${{ variables.spec_file }}
    enable_monitoring: true
    enable_status_monitoring: true
    jinja_templates:
      REQUIRE_ASID: false
      PDS_TARGET_SERVER: spine-demographics
    secret_ids:
      - ptl/app-credentials/jwt_testing/non-prod/JWT_TESTING_API_KEY
      - ptl/app-credentials/jwt_testing/non-prod/JWT_TESTING_WITH_ASID_API_KEY
    secret_file_ids:
      - ptl/app-credentials/jwt_testing/non-prod/JWT_TESTING_WITH_ASID_PRIVATE_KEY
      - ptl/app-credentials/jwt_testing/non-prod/JWT_TESTING_PRIVATE_KEY
    apigee_deployments:
      - environment: internal-dev
        make_spec_visible: true
        post_deploy:
          - template: templates/pds-tests.yml
            parameters:
              test_pack_path: ./e2e/smoke.json
              test_type: smoke
      - environment: internal-qa
        make_spec_visible: true
        post_deploy:
          - template: templates/pds-tests.yml
            parameters:
              test_pack_path: ./e2e/smoke.json
              test_type: smoke
      - environment: internal-qa-sandbox
        make_spec_visible: true
        proxy_path: sandbox
      - environment: int
        make_spec_visible: true
        depends_on:
          - internal_qa
          - internal_qa_sandbox
      - environment: ref
        make_spec_visible: true
        depends_on:
          - internal_qa
          - internal_qa_sandbox
      - environment: sandbox
        proxy_path: sandbox
        depends_on:
          - internal_qa
          - internal_qa_sandbox
      - environment: prod
        make_spec_visible: true
        depends_on:
          - internal_qa
          - internal_qa_sandbox
        jinja_templates:
          REQUIRE_ASID: true
          PDS_TARGET_SERVER: spine-demographics
