name: application-restricted # Will have SERVICE_NAME- prepended to this
displayName: Personal Demographics Service - Application Restricted
description: Access the Personal Demographics Service with reduced permisions.
scopes:
  - access_mode:APPLICATION-RESTRICTED
environments:
  - internal-dev
  - internal-dev-sandbox
  - internal-qa
  - internal-qa-sandbox
  - sandbox
  - dev
  - int
  